### ISSUE TITLE
Error when run order.py

### ISSUE THREAD

**Issue by CGod1991** [xjqicuhk/SIMS#7]
I was perform the inference on my own semantic masks with resolution "1024 * 2048". According the "Inference" part says, first run test_connect_component_mask.m、search_segments.m、test_generate_transform.m、transformation.py and test_generate_order.m, it's all good. But when run the order.py i got this error:
`Traceback (most recent call last):
  File "/home/x00478666/pycharm-community-2018.2/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/x00478666/pycharm-community-2018.2/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/x00478666/pycharm-community-2018.2/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/x00478666/pycharm-community-2018.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/distributed-training/x00478666/SIMS/SIMS-master/python_code/order.py", line 259, in <module>
    sess.run(proposal_score, feed_dict={data: tmp_data}))
ValueError: could not broadcast input array from shape (4,5,20) into shape (1,20)`

and in order.py i set this:
`batch_size = 1
crop_size_h = 1024
crop_size_w = 2048
input_dim = 6`

Did i miss something?
Best regards.

**Comment by xjqicuhk** [comment]
It's caused by the input  "data: tmp_data" cannot fit the parameters
defined in the place holder for variable "proposal_score"
